### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by chope1** [Sweetdevil144/Youtube-Shorts-Creator#14]
Trying to install locally, getting this error -
`PS C:\Users\MSI\Youtube-Shorts-Creator> node index.js
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module 'C:\Users\MSI\Youtube-Shorts-Creator\index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`

Tried with Vercel and still getting 404 error -
https://youtube-shorts-creator.vercel.app/

**Comment by Sweetdevil144** [comment]
```javascript
"scripts": {
    "start": "node api/app.js",
    "dev": "nodemon api/app.js",
    "format": "prettier --check --ignore-path .gitignore .",
    "format:fix": "prettier --write --ignore-path .gitignore ."
  },
```

**Comment by Sweetdevil144** [comment]
The vercel and render instances are down due to key management. however, it will work locally right now (i hope so).
