### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by akeslo** [Sweetdevil144/Youtube-Shorts-Creator#6]
╰─$ node app    
Server is running on port 3000
Error
{
  message: 'Invalid API key. Go to https://docs.rapidapi.com/docs/keys for more info.'
}
Caught error in app.js
An Error occurred -> TypeError: Cannot read properties of undefined (reading 'transcript')

**Comment by Sweetdevil144** [comment]
Soryy, but the website seems to be working perfectly fine on render.com. Can you try these following steps to start this in localhost ?
+ Create a .env file
+ Go to [RapidAPI](https://rapidapi.com/hub) and select [this](https://rapidapi.com/eaidoo015-pj8dZiAnLJJ/api/youtube-scraper-2023/) API. Subscript it for free.
+ Within the `.env` filecreate the following : 
+ - OPENAI_API_KEY (Get it from openai's api section)
+ - Rapid_API_KEY (From RapidAPI)
+ Set the api keys like following:
+ - Rapid_API_KEY=<Your API Key without colons> , and similarly for OPENAI_API_KEY.

**Comment by akeslo** [comment]
Thanks, didn't see Rapid_API_Key listed in readme so I missed this. I was able to add it and got passed this error but hit something new.
